"""Initial migration

Revision ID: 84c4f6b87dd2
Revises: 
Create Date: 2026-05-16 11:51:19.908259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c4f6b87dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('sender', sa.String(length=100), nullable=True),
    sa.Column('handle', sa.String(length=50), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('media_url', sa.String(length=200), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('bookmarks', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('node', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.String(length=50), nullable=True),
    sa.Column('is_retweet', sa.Boolean(), nullable=True),
    sa.Column('original_post_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['original_post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('handle', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=200), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=200), nullable=True),
    sa.Column('account_tier', sa.String(length=20), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('handle'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('chat_group',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=True),
    sa.Column('user2_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user1_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follow_requests',
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requested_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], )
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('notification',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_like',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('story',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_url', sa.String(length=200), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_group_members',
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('group_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['chat_group.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('group_message')
    op.drop_table('chat_group_members')
    op.drop_table('story')
    op.drop_table('post_like')
    op.drop_table('notification')
    op.drop_table('followers')
    op.drop_table('follow_requests')
    op.drop_table('conversation')
    op.drop_table('chat_group')
    op.drop_table('user')
    op.drop_table('post')
    # ### end Alembic commands ###
